root: true
env:
  node: true
ignorePatterns:
  - "node_modules"
  - "dist"

plugins: ["@typescript-eslint"]
extends:
  - "eslint:recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:astro/recommended"
  - "prettier"

parser: "@typescript-eslint/parser"

overrides:
  - files: ["*.astro"]
    parser: "astro-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions: [".astro"]
    rules:
      "prettier/prettier": "off"
      "@typescript-eslint/no-unused-vars":
        - "warn"
        - varsIgnorePattern: "Props"
          ignoreRestSiblings: true
